DemoCatalog/MyCatalog/Models/ErrorViewModel.cs
using System;

namespace MyCatalog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoCatalog/MyCatalog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyCatalog.Service;

namespace MyCatalog.Controllers
{
    public class CategoryController : Controller
    {
        public MyDbContext DbContext { get; set; }

        public CategoryController(MyDbContext db)
        {
            this.DbContext = db;
        }

        public IActionResult Categorie(int page = 0, int size = 5)
        {
            int position = page * size ;
            IEnumerable<Category> categories = DbContext.Categories.Skip(position).Take(size).ToList();
            ViewBag.currentPage = page;
            int lenghtOfList = DbContext.Categories.ToList().Count % size;
            int totalPages = DbContext.Categories.ToList().Count / size;
            ViewBag.totalPages = (lenghtOfList == 0) ? totalPages : totalPages + 1;
            return View("Categorie", categories);
        }

        public IActionResult CreateCategory()
        {
            
                Category c = new Category();
                return View("CreateCategory", c);

        }
        [HttpPost]
        public IActionResult SaveCategory(Category c )
        {
            if (ModelState.IsValid)
            {
                DbContext.Categories.Add(c);
                DbContext.SaveChanges();

                return RedirectToAction("Categorie");
            }
            else
            {
                return View("CreateCategory");

            }
        }

        
        public IActionResult EditForm(int? CategoryId)
        {
            Category c = DbContext.Categories.Find(CategoryId);
            return View("EditForm", c);
        }


        [HttpPost] 
        public IActionResult SaveEdit(Category c )
        {
            DbContext.Categories.Update(c);
            DbContext.SaveChanges();
            return RedirectToAction("Categorie");
        }


        public IActionResult DetailsCategory(int? CategoryId)
        {
            Category c = DbContext.Categories.Find(CategoryId);
            return View("DetailsCategory",c);
        }

        public IActionResult DeleteForm(int? CategoryId)
        {
            Category c = DbContext.Categories.Find(CategoryId);
            return View("DeleteForm", c);
        }


        public IActionResult DeleteItem(Category c)
        {
            DbContext.Categories.Remove(c);
            DbContext.SaveChanges();
            return RedirectToAction("Categorie");
        }
    }
}

DemoCatalog/MyCatalog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCatalog.Models;

namespace MyCatalog.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoCatalog/MyCatalog/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyCatalog.Service;

namespace MyCatalog.Controllers
{
    public class ProduitController : Controller
    {
        public MyDbContext DbContext { get; set; }

        public ProduitController(MyDbContext db)
        {
            this.DbContext = db;  
        }
        public IActionResult Index(int page = 0, int size = 5,string motCle = "")
        {
            int position = page * size;
            IEnumerable<Product> produits = DbContext.Produits
                .Where(p=>p.Designation.Contains(motCle))
                .Skip(position)
                .Take(size)
                .Include(p=>p.Category)
                .ToList();

            ViewBag.currentPage = page;
            int lenghtOfList = DbContext.Produits.Where(p => p.Designation.Contains(motCle)).ToList().Count % size;
            int totalPages = DbContext.Produits.Where(p => p.Designation.Contains(motCle)).ToList().Count / size;
            ViewBag.totalPages = (lenghtOfList == 0) ? totalPages : totalPages + 1;
            ViewBag.motCle = motCle;
            return View("Produits",produits);
        }

        public IActionResult CreateFrom()
        {
            Product p = new Product();
            Categorie();
            return View("CreateFrom", p);
        }


        [HttpPost]
        public IActionResult SaveProduit(Product p,string Designation)
        {
            Product produit = DbContext.Produits.Find(Designation);

            if (ModelState.IsValid && ! p.Designation.Equals(produit))
            {
                DbContext.Produits.Add(p);
                DbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                Categorie();
                return View("CreateFrom");

            }
        }
        public IActionResult EditFrom(int? ProductId)
        {
            Product p = DbContext.Produits.Find(ProductId);
            Categorie();
            return View("EditFrom",p);
        }


        [HttpPost]
        public IActionResult Editsave(Product p)
        {
            
            DbContext.Produits.Update(p);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public void Categorie()
        {
            IEnumerable<Category> cats = DbContext.Categories.ToList();
            ViewBag.categories = cats;
        }

        public IActionResult DeleteForm(int? ProductId)
        {
            Product p = DbContext.Produits.Find(ProductId);
            Categorie();
            return View("DeleteForm",p);
        }

        public IActionResult DeleteItem(Product p)
        {
            DbContext.Produits.Remove(p);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }

     
        public IActionResult DetailsProduct(int? ProductId)
        { 
           Product p = DbContext.Produits.Find(ProductId);
            Categorie();
            return View("DetailsProduct");
        }
        public IActionResult ToSwitch()
        {
            return RedirectToAction("Categorie","Category");
        }
       
    }
}

DemoCatalog/MyCatalog/Views/Category/Categorie.cshtml
@model IEnumerable<MyCatalog.Service.Category>

@{
    ViewData["Title"] = "Categorie";
}

<h2>Categorie</h2>

<p>
    <a asp-action="CreateCategory">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Categoryname)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoryname)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditForm", new { CategoryId = item.CategoryId })
                    @Html.ActionLink("Details", "DetailsCategory", new { CategoryId = item.CategoryId })
                    @Html.ActionLink("Delete", "DeleteForm", new { CategoryId = item.CategoryId })
                </td>
            </tr>
        }
    </tbody>

</table>
<div>
    <ul class=" nav nav-pills">
        @{
            for (int i = 0; i < ViewBag.totalPages; i++)
            {
                string className = "";

                if (i == ViewBag.currentPage)
                {
                    className = "active";
                }
                <li class="@className">
                    <a asp-action="Categorie" asp-route-page="@i">@(i + 1)</a>
                </li>
            }
        }

    </ul>
</div>

DemoCatalog/MyCatalog/Views/Category/CreateCategory.cshtml
@model MyCatalog.Service.Category

@{
    ViewData["Title"] = "CreateCategory";
}

<h2>CreateCategory</h2>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SaveCategory" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Categoryname" class="control-label"></label>
                <input asp-for="Categoryname" class="form-control" />
                <span asp-validation-for="Categoryname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Categorie">Back to List</a>
</div>

DemoCatalog/MyCatalog/Views/Category/DeleteForm.cshtml
@model MyCatalog.Service.Category

@{
    ViewData["Title"] = "DeleteForm";
}

<h2>DeleteForm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoryname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoryname)
        </dd>
    </dl>
    
    <form asp-action="DeleteItem" method="post">
        <input type="hidden" asp-for="CategoryId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Categorie">Back to List</a>
    </form>
</div>

DemoCatalog/MyCatalog/Views/Category/DetailsCategory.cshtml
@model MyCatalog.Service.Category

@{
    ViewData["Title"] = "DetailsCategory";
}

<h2>DetailsCategory</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoryname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoryname)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CategoryId">Edit</a> |
    <a asp-action="Categorie">Back to List</a>
</div>

DemoCatalog/MyCatalog/Views/Category/EditForm.cshtml
@model MyCatalog.Service.Category

@{
    ViewData["Title"] = "EditForm";
}

<h2>EditForm</h2>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SaveEdit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="Categoryname" class="control-label"></label>
                <input asp-for="Categoryname" class="form-control" />
                <span asp-validation-for="Categoryname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Categorie">Back to List</a>
</div>

DemoCatalog/MyCatalog/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DemoCatalog/MyCatalog/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DemoCatalog/MyCatalog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

DemoCatalog/MyCatalog/Views/Produit/CreateFrom.cshtml
@model MyCatalog.Service.Product

@{
    ViewData["Title"] = "CreateFrom";
}

<h2>CreateFrom</h2>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="SaveProduit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <input asp-for="Designation" asp-route-Designation="@ViewBag.Designation" class="form-control" />
                <span asp-validation-for="Designation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId">
                    @{ 
                        foreach(var item in ViewBag.categories )
                        {
                        <option value="@item.CategoryId">@item.Categoryname</option>
                        }
                     }

                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DemoCatalog/MyCatalog/Views/Produit/DeleteForm.cshtml
@model MyCatalog.Service.Product

@{
    ViewData["Title"] = "DeleteForm";
}

<h2>DeleteForm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantite)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantite)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Categoryname)
        </dd>
    </dl>
    
    <form asp-action="DeleteItem">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoCatalog/MyCatalog/Views/Produit/DetailsProduct.cshtml
@model MyCatalog.Service.Product

@{
    ViewData["Title"] = "DetailsProduct";
}

<h2>DetailsProduct</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantite)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantite)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DemoCatalog/MyCatalog/Views/Produit/EditFrom.cshtml
@model MyCatalog.Service.Product

@{
    ViewData["Title"] = "EditFrom";
}

<h2>EditFrom</h2>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Editsave" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type ="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <input asp-for="Designation" class="form-control"/>
                <span asp-validation-for="Designation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId">
                    @{
                        foreach (var item in ViewBag.categories)
                        {
                            <option value="@item.CategoryId">@item.Categoryname</option>
                        }
                    }

                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DemoCatalog/MyCatalog/Views/Produit/Produits.cshtml
@model IEnumerable<MyCatalog.Service.Product>

@{
    ViewData["Title"] = "Produits";
}

<h2>Produits</h2>

<p>
    <a asp-action="CreateFrom">Add new Product </a>
    <a asp-action="ToSwitch">List Category</a>
</p>

<table class="table">
  
    <thead>
        <div class="container">
            <form method="get" asp-action="Index">
                <label>Mot cle : </label>
                <input type="text" name="motCle" />
                <button type="submit" class="btn btn-primary">Search </button>
            </form>
        </div>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Designation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Categoryname)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditFrom", new { ProductId = item.ProductId })
                    @Html.ActionLink("Details", "DetailsProduct", new { ProductId = item.ProductId })
                    @Html.ActionLink("Delete", "DeleteForm", new { ProductId = item.ProductId })
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <ul class=" nav nav-pills">
        @{
            for (int i = 0; i < ViewBag.totalPages; i++)
            {
                string className = "";

                if (i == ViewBag.currentPage)
                {
                    className = "active";
                }
                <li class="@className">
                    <a asp-action="Index" asp-route-page="@i" asp-route-motCle="@ViewBag.motCle">@(i + 1)</a>
                </li>
            }
        }

    </ul>
    <form method="get" asp-action="Index">
        <button type="submit"  class="btn btn-primary"  >Back To All Product </button>
    </form>
</div>

DemoCatalog/MyCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCatalog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyCatalog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Produit" asp-action="Index">Produit</a></li>
          
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MyCatalog</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>